import { Html5Audio, Sequence, interpolate, staticFile } from "remotion";

// Sound design. Brand rule: no music — only nasheeds without percussion,
// plus non-musical effects. Effects are generated by scripts/make-sfx.py.
export type Sfx = "whoosh" | "impact" | "hit" | "riser";

const LENGTH: Record<Sfx, number> = {
  whoosh: 17,
  impact: 42,
  hit: 11,
  riser: 48,
};

const VOLUME: Record<Sfx, number> = {
  whoosh: 0.7,
  impact: 0.6,
  hit: 0.45,
  riser: 0.65,
};

// Plays one effect starting at `at` (frames).
export const SoundEffect: React.FC<{ type: Sfx; at: number }> = ({
  type,
  at,
}) => (
  <Sequence from={at} durationInFrames={LENGTH[type]} layout="none">
    <Html5Audio src={staticFile(`sfx/${type}.wav`)} volume={VOLUME[type]} />
  </Sequence>
);

// Background bed: a nasheed (no percussion) from public/audio/ when given,
// otherwise a quiet dark room tone (60 s long, longer than any Reel). Fades in and out.
export const Bed: React.FC<{ nasheed?: string; duration: number }> = ({
  nasheed,
  duration,
}) => {
  const level = nasheed ? 0.35 : 0.18;
  const volume = (f: number) =>
    interpolate(f, [0, 20, duration - 30, duration], [0, level, level, 0], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    });
  return (
    <Html5Audio src={staticFile(nasheed ?? "sfx/room.mp3")} volume={volume} />
  );
};
